solr:
    build: docker/solr
    hostname: solr
    domainname: localdomain
    ports:
    - "8983:8983"
    volumes:



geodropdownservice:
    ports:
    - "8080:80"
    
    
    links:
        - postgres:postgres
        - solr:solr
        