solr:
    build: docker/solr
    hostname: solr
    ports:
    - "8983:8983"



geodropdownservice:
    build: bioinformaticsua/geodropdownservice
    ports:
    - "8886:80"
    
    links:
        - postgres:postgres
        - solr:solr
        