solr:
    image: solr:5.5.3
    hostname: solr
    ports:
        - "8887:8983"



geodropdownservice:
    image: bioinformaticsua/geodropdownservice
    ports:
        - "8886:80"
    volumes:
        - .:/opt/django/app
    links:
        - solr:solr
        
